README.md
lua/nvim-paredit/defaults.lua
lua/nvim-paredit/init.lua
lua/nvim-paredit/utils/common.lua
lua/nvim-paredit/utils/keybindings.lua

- fix: keybinds wasn't attached to initial buffer because autocommand's callback is not called immediately and user had to reload a file.
- feat: add filetypes option which overrides lang.filetypes(). In some cases user may restrict keybinds attach to certain types only. Also filters out extra unsupported filetypes.

feat: add filetype option + assign keys immediately on init

---

lua/nvim-paredit/api/motions.lua
tests/nvim-paredit/motion_spec.lua

TIL, comments range takes +1 extra line at the end
```
(+ 1 1)
;; my-comment
(+ 2 2)
```
in this example the comment form's range is {1,0, 2,0}, but not {1,0, 1,13}
This fix utilizes `vcount` feature, if cursor is inside comment just increase `vcount` by 1 to make one extra move

fix #15 motions bug

---

lua/nvim-paredit/init.lua

As per the installation instructions, passing no parameters to `setup()` should not break

Allow passing no opts to setup()

---

README.md
lua/nvim-paredit/api/deletions.lua
lua/nvim-paredit/api/init.lua
tests/nvim-paredit/deletions_spec.lua

This implements a set of API's for deleting nodes and forms.
+ `delete_form` - Delete the entire form under the cursor
+ `delete_in_form` - Deletes all elements within the form under the cursor
+ `delete_element` - Deletes the element under the cursor
Addresses #12
---
This isn't entirely what we need as I would expect this to be broken up further into form/element selection API's and then implement the deletions on top thereof.
I don't yet know how text object selections work in vim, so I just hacked this together in the meantime.
I am not assigning any default keybindings to these as I expect long term we actually want this to work out-of-the-box with text object selections.

Add API's for various deletion operations

---

README.md
lua/nvim-paredit/api/deletions.lua
lua/nvim-paredit/api/init.lua
lua/nvim-paredit/api/selections.lua
lua/nvim-paredit/defaults.lua
lua/nvim-paredit/utils/keybindings.lua
tests/nvim-paredit/text_object_selections_spec.lua
tests/nvim-paredit/utils.lua

This builds on top of the previous form/element deletions work by expanding it to work for text object selections.
This allows constructing selections within/around forms and elements which can be operated on natively by `d`, `c`, `y` and friends.
Closes #12

Add text object selections for forms and elements

---

README.md
lua/nvim-paredit/api/motions.lua
lua/nvim-paredit/defaults.lua
lua/nvim-paredit/utils/common.lua
lua/nvim-paredit/utils/keybindings.lua
tests/nvim-paredit/operator_motion_spec.lua
tests/nvim-paredit/text_object_selections_spec.lua

Currently the E/B motions are configured with `operator = true` which additionally adds the `o` mode keymap with the fn wrapped in `normal! v` to allow it to function in operator-pending mode.
This moves responsibility into the keymap setup phase instead of the function handling the action, and in the current implementation won't work in visual mode operator-pending states.
This commit shifts the responsibility to the motions API by allowing them to detect the current mode and conditionally set `normal! v`.

Replace `operator` keymap field with smarter funcs

---

lua/nvim-paredit/defaults.lua

The default keymaps for slurping and barfing backwards were the wrong way around with respect to the mappings defined by mappings-for-regular-people.
This was a mistake and is better resolved early on while it doesn't affect too many people.
Closes #23

Swap default slurp/barf backwards keymaps

---

README.md
lua/nvim-paredit/api/selections.lua
lua/nvim-paredit/defaults.lua
tests/nvim-paredit/text_object_selections_spec.lua

No element-wise keymaps were included in #21. This adds them

Add ae/ie text-selection keymaps for elements

---

lua/nvim-paredit/api/cursor.lua
lua/nvim-paredit/api/wrap.lua
tests/nvim-paredit/cursor_spec.lua
tests/nvim-paredit/form_and_element_wrap_spec.lua

Fixes issue when cursor is not placed correctly in some cases.
Solution: return range instead of node.
- all wrap functions now returns a wrapped range instead of a node (breaking)
- cursor.place_cursor now accepts either range as a table or a TSNode (backwards compatible)
This PR fixes the issue when `ts.get_node_at_cursor` returns different nodes depending on where the cursor is located.
Here are two tests, first one fails (when the cursor at the beginning of a node), but the second test works as expected.
```lua
it("ts check fails", function()
prepare_buffer({
content = { "(a (b))" },
cursor = { 1, 3 },
})
paredit.wrap.wrap_element_under_cursor("( ", ")")
local parser = vim.treesitter.get_parser(0, vim.bo.filetype)
parser:parse()
local node = ts.get_node_at_cursor()
-- here the …
```

fix!: wrap functions returns different node depending on cursor position

---

lua/nvim-paredit/utils/keybindings.lua

This allows disabling specific keymaps. This allows using the defaults but overriding specific keymaps.

Allow setting keymaps to nil to disable

---

README.md
lua/nvim-paredit/init.lua

When extensions are lazy loaded on `ft` event they need to attach themselves to the buffer after they have registered themselves.

Configure keymaps when new language API is added

---

README.md
lua/nvim-paredit/api/barfing.lua
lua/nvim-paredit/api/slurping.lua
lua/nvim-paredit/config.lua
lua/nvim-paredit/defaults.lua
lua/nvim-paredit/indentation/init.lua
lua/nvim-paredit/indentation/native.lua
lua/nvim-paredit/indentation/utils.lua
lua/nvim-paredit/init.lua
lua/nvim-paredit/utils/common.lua
tests/nvim-paredit/indentation_spec.lua

This adds support for automatic indentation correction when slurping and barfing.
The goal of this implementation is to:
1) Provide a visual aid to the user that allows them to confirm they are operating on the correct node, and to know when to stop when performing recursive slurp/barf operations.
2) Be simple to maintain and understand while being as correct as possible
3) Be replaceable with other implementations.
4) Be as performant as possible. There should be no lag or visual jitter
The goal is _not_ to be 100% correct. If a more correct implementation is needed then one can be provided through `indent_fn`. For example, an implementation using `vim.lsp.buf.format` could be built if the user doesn't mind sacrificing performance for correctness.

Add support for form indentation on slurp/barf

---

lua/nvim-paredit/utils/keybindings.lua

The return statement was breaking out of the entire loop.

Don't use return in a loop

---

README.md

I was getting this kind of error: 
```
paredit.lua:31: attempt to index global 'paredit' (a nil value)
```
The proposed changes fixed for me.
I don't use lazy.nvim and I'm not sure if the original works with it.
I'm also not versed in `lua` so feel free to adjust anything codewise.

fix typo in lua default config file sample

---

README.md
lua/nvim-paredit/api/deletions.lua
lua/nvim-paredit/api/init.lua
lua/nvim-paredit/api/selections.lua
lua/nvim-paredit/defaults.lua
lua/nvim-paredit/utils/traversal.lua
tests/nvim-paredit/text_object_selections_spec.lua

Could maybe do with more methods and tests, but this is already working and the tests are passing. I haven't checked visual selections yet, I presume I will need to add more functions and mappings for that.
The general tree sitter / selection code seems to be working though. I might also refactor this a bit to reuse code between the "current form" and "top level form" functions. There's a lot of overlap there but I thought I'd take the simple copy/paste approach first.
Also I went with "top level" to describe this concept, in my tooling I call it "root" but you already have terms for root and I didn't want to muddy those waters.

Initial pass with top level form selection and deletion

---

README.md
lua/nvim-paredit/api/init.lua
lua/nvim-paredit/api/motions.lua
lua/nvim-paredit/defaults.lua
lua/nvim-paredit/utils/common.lua
tests/nvim-paredit/motion_spec.lua

fixes #37
Here is config example:
```lua
["E"] = {
paredit.api.move_to_next_element_tail,
"Jump to next element tail",
-- by default all keybindings are dot repeatable
repeatable = false,
mode = { "n", "x", "o", "v" },
},
["W"] = {
paredit.api.move_to_next_element_head,
"Jump to next element head",
repeatable = false,
mode = { "n", "x", "o", "v" },
},
["B"] = {
paredit.api.move_to_prev_element_head,
"Jump to previous element head",
repeatable = false,
mode = { "n", "x", "o", "v" },
},
["gE"] = {
paredit.api.move_to_prev_element_tail,
"Jump to previous element tail",
repeatable = false,
mode = { "n", "x", "o", "v" },
},
```
- `paredit.api.move_to_next_element` is deprecated in favour of `paredit.api.move_to_next_element_tail`
- `paredit.api.move_to_prev_element` is deprecated in favour of …

feat(#37): head tail movement support + deprecate previous API's

---

README.md
lua/nvim-paredit/api/init.lua
lua/nvim-paredit/api/motions.lua
lua/nvim-paredit/defaults.lua
tests/nvim-paredit/motion_spec.lua

feat(motion): allows movement to parent form's edges using `(, )`

---

README.md

I think this part of the readme is old, because only `require("nvim-paredit")` worked for me.

docs: fix api documentation for wrap form

---

README.md
lua/nvim-paredit/api/unwrap.lua
lua/nvim-paredit/defaults.lua
lua/nvim-paredit/init.lua
tests/nvim-paredit/form_unwrap_spec.lua

add following keybinding:
```lua
["<localleader>@"] = {
paredit.unwrap.unwrap_form_under_cursor,
"Splice sexp",
},
```

feat: Splice api (fixes #43)

---

lua/nvim-paredit/api/motions.lua
lua/nvim-paredit/utils/traversal.lua
tests/nvim-paredit/motion_spec.lua
tests/nvim-paredit/operator_motion_spec.lua

- `move_to_next_element_head` now becomes exclusive when operator mode is active.
- also it acts as `move_to_next_element_tail` when there is no next element available (only in non `reversed` mode), same logic as native `w` motion.

fixes #42: Exclusive motion support

---

README.md

The extensions' documentation has a wrong function name I think.
Thanks for the plugin!
I'm making a Scheme extension and I found this. I'll ping you when I have it!

FIX docs: get_node_edges => get_form_edges

---

README.md

Using this PR to let you know about my Scheme extension.
I think it mostly works, but I had a hard time making it understand the difference between a standard comment (`;`) and a comment from the srfi 62 (`#;`) that affects the following expression. I'm not sure about how to deal with some other things either but I'll go improving it as I use it in my everyday work (I'm a heavy scheme user).
Thanks for this plugin, it's cool that it's based on treesitter, I was using vim-paredit before, which is based on regular expressions and has a lot of issues with large files. I had a lot of out of sync issues... it was hard to deal with.
This is way better!
I'll let you know about my experience using this.

Add scheme extension to list

---

lua/nvim-paredit/api/cursor.lua

Current implementation uses `vim.api.nvim_feedkeys` which is slower whan `vim.cmd("startinsert")` due to more general nature (async?) of an API.
Sometimes when user (me 😃) presses `,w`/`,W` (wrap + insert mode) and immediately starts typing the text input gets broken because insert mode is not still activated, `startinsert` is way more faster and solves this issue.

fix: use vim.cmd instead of feedkeys

---

.github/workflows/test.yml
Justfile

This reworks the test command to work better when switching between different nvim channels. Currently the .build/nvim dir needs to be deleted manually when switching to a different channel but now different channels are downloaded to separate directories.
Additionally this adds support for specifying an individual file to run the tests for which improves the developer experience of working on tests.

Rework test command to be more flexible

---

.github/workflows/test.yml
lua/nvim-paredit/api/barfing.lua
tests/nvim-paredit/barf_spec.lua

This fixes some inconsistencies with the cursor_behaviour logic during barf operations that was revealed by the neovim nightly release.
Closes #56

Fix barf specs on nightly

---

lua/nvim-paredit/lang/init.lua

My Neovim setup uses a compound filetype such as `scheme.guile`, which is documented in `:h 'filetype'` as follows:
```
|FileType| |filetypes|
When a dot appears in the value then this separates two filetype
names.  Example:
/* vim: set filetype=c.doxygen : */
This will use the "c" filetype first, then the "doxygen" filetype.
This works both for filetype plugins and for syntax files.  More than
one dot may appear.
```
This distinction is important, amongst other things, so that [Conjure](https://github.com/Olical/conjure/) select the correct client for the particular dialect of Scheme.  However, currently, `nvim-paredit` chokes on this, even though a valid configuration for `scheme` is available (I am using [nvim-paredit-scheme](http://git.elenq.tech/nvim-paredit-scheme/)), because …

Try all parts of a compound filetype

---

lua/nvim-paredit/lang/clojure.lua
tests/nvim-paredit/barf_spec.lua
tests/nvim-paredit/element_raise_spec.lua
tests/nvim-paredit/form_raise_spec.lua
tests/nvim-paredit/form_unwrap_spec.lua
tests/nvim-paredit/slurp_spec.lua
tests/nvim-paredit/text_object_selections_spec.lua

Add support for reader conditional forms, e.g.
```clojure
#?(:clj ... 
:cljs ...)
```

fix: adds `read_cond_lit` treesitter node

---

lua/nvim-paredit/api/motions.lua
tests/nvim-paredit/operator_motion_spec.lua

There was some overflow issues when using B/W keybindings in operator pending mode.

Fix B/W overflow error in operator pending mode

---

README.md
lua/nvim-paredit/api/dragging.lua
lua/nvim-paredit/api/init.lua
lua/nvim-paredit/api/selections.lua
lua/nvim-paredit/defaults.lua
lua/nvim-paredit/lang/clojure.lua
lua/nvim-paredit/lang/init.lua
lua/nvim-paredit/utils/common.lua
lua/nvim-paredit/utils/traversal.lua
lua/nvim-paredit/utils/ts.lua
plugin/nvim-paredit.vim
queries/clojure/paredit/pairwise.scm
tests/nvim-paredit/pair_drag_spec.lua

This adds two new APIs - `drag_pair_forwards` and its companion `drag_pair_backwards` which allow dragging 'pairs' of elements within a form.
An easy example is the key-value pairs within a map which typically are meant to stay together when reordering.
This can, however, be used for any form. This means if you have some vector containing logical pairs (because of the actual semantics of your code) you can use a dedicated keybinding to drag them around together.
This change also introduces a new config option at:
`dragging.auto_drag_pairs = true|false`
which will alter the behaviour of the existing `drag_element_forwards` and `drag_element_backwards` APIs in order to try infer whether they are contained within a node that is made up of pairs.
For example if this setting is `true` and a …

Pairwise dragging

---

README.md
docs/api-reference.md
docs/language-extension-spec.md
docs/recipes.md
lua/nvim-paredit/api/init.lua
lua/nvim-paredit/api/wrap.lua
lua/nvim-paredit/defaults.lua
lua/nvim-paredit/utils/common.lua

This current documentation was getting a bit out of date and out of hand. Not everything was documented, some things were documented incorrectly and everything was in a single file.
This updates the documentation to be up-to-date with the current state of our API's and splits certain aspects into new files under `./docs`

Revamp documentation

---

lua/nvim-paredit/defaults.lua
queries/fennel/paredit/forms.scm
tests/config.lua
tests/nvim-paredit/fennel/element_raise_spec.lua
tests/nvim-paredit/fennel/form_raise_spec.lua
tests/nvim-paredit/fennel/motion_spec.lua
tests/nvim-paredit/fennel/slurp_spec.lua

This adds fennel treesitter grammars to nvim-paredit which effectively gives us out-of-the box fennel support.
This effectively supersedes https://github.com/julienvincent/nvim-paredit-fennel

Add fennel support

---

lua/nvim-paredit/defaults.lua
queries/scheme/paredit/forms.scm
tests/config.lua
tests/nvim-paredit/scheme/element_raise_spec.lua
tests/nvim-paredit/scheme/form_raise_spec.lua
tests/nvim-paredit/scheme/motion_spec.lua
tests/nvim-paredit/scheme/slurp_spec.lua

This adds scheme treesitter grammars to nvim-paredit which effectively gives us out-of-the box scheme support.
This effectively supersedes https://github.com/ekaitz-zarraga/nvim-paredit-scheme

Add scheme support

---

lua/nvim-paredit/indentation/native.lua
lua/nvim-paredit/indentation/utils.lua
tests/nvim-paredit/barf_spec.lua
tests/nvim-paredit/deletions_spec.lua
tests/nvim-paredit/element_drag_spec.lua
tests/nvim-paredit/element_raise_spec.lua
tests/nvim-paredit/form_and_element_wrap_spec.lua
tests/nvim-paredit/form_drag_spec.lua
tests/nvim-paredit/form_raise_spec.lua
tests/nvim-paredit/form_unwrap_spec.lua
tests/nvim-paredit/indentation_spec.lua
tests/nvim-paredit/motion_spec.lua
tests/nvim-paredit/operator_motion_spec.lua
tests/nvim-paredit/pair_drag_spec.lua
tests/nvim-paredit/slurp_spec.lua
tests/nvim-paredit/text_object_selections_spec.lua

There are a few cases, especially when comments are involved, where the indent would break or do the wrong thing.
This adds some more tests for edge-cases and fixes the behaviour for those cases.

Improve native indent impl under some edge cases

---

lua/nvim-paredit/treesitter/pairs.lua
tests/nvim-paredit/pair_drag_spec.lua

The pairwise drag implementation would collect all nodes marker as a pair within the local node tree.
This means that pairs found and other levels in the tree were considered for dragging and would allow eroneously dragging pairs outside of form  boundaries.
This fixes the issue by first filtering the matches nodes by those contained within the current form.

Fix pairwise drag dragging beyond form boundaries

---

lua/nvim-paredit/api/dragging.lua
lua/nvim-paredit/api/text.lua
lua/nvim-paredit/treesitter/pairs.lua
tests/nvim-paredit/motion_spec.lua
tests/nvim-paredit/pair_drag_spec.lua

Currently when performing a swap, each element in a pair is swapped with it's corresponding paired element.
This works for simple cases but breaks when the number of lines are different between the two pairs as the ranges the nodes represent have now changed from previous edits.
This fixes the issue by finding the full range represented by both elements in a pair and swapping this entire range in one go.

Swap both elements of a pair together
